### ISSUE TITLE
Security Issue (Amazon RDS)

### ISSUE THREAD

**Issue by ousamabenyounes** [cristid9/FunWeb#28]
Hi @cristid9 

your Amazon RDS credentials are visible here: https://github.com/cristid9/FunWeb/blob/4ede5f5cabe306ae85c3c89946d880f8f6e99992/funweb-code/src/main/webapp/WEB-INF/config.properties

to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects...If you use this password.

**Comment by cristid9** [comment]
Hi @ousamabenyounes those are some mock credentials. These are not the valid ones.

**Comment by ousamabenyounes** [comment]
Hi @cristid9,

I'm working on a bot script to help me find last indexed files wich contains sensible credentials.
So it will help me to automatically open security issues and then help developpers protect their projects.

I'm trying to do some "ethical hacking" and I really love to see developper really happy when they discover this critical mistake...Lot of hackers use github to get some sensible informations.
Gmail, Paypal, Amazon and so on...
I work hard to understand all way we can use to find your credentials, and my main goal is only to warm them.

Regards,
Ousama.

**Comment by cristid9** [comment]
Cool!
